package org.wynnvets.mixin.client;

import net.minecraft.client.gui.components.ChatComponent;
import net.minecraft.network.chat.Component;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Inject;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfo;
import org.wynnvets.fetcher.polling.BridgeMessageFetcher;
import org.wynnvets.chat.ChatLogger;
import org.wynnvets.guild.GuildStateManager;
import org.wynnvets.chat.ChatUtils;
import org.wynnvets.chat.rewriter.ServerGuildChatRewriter;
import org.wynnvets.chat.rewriter.StaffChannelMessageRewriter;
import org.wynnvets.chat.rewriter.StaffGuildAlertRewriter;
import org.wynnvets.chat.StaffOutboundMessenger;
import org.wynnvets.logging.VetsLogger;

/**
 * Intercepts all incoming chat messages via {@link ChatComponent#addMessage}.
 *
 * <p>This is the primary chat pipeline hook. It performs, in order:
 * logging to file, guild state detection, mod-initiated message suppression,
 * staff outbound feedback suppression, Fruma-mode duplicate suppression,
 * and chat rewriting (staff alerts, staff channel, supporter gradients).
 * Messages generated internally by the mod are passed through unmodified.</p>
 */
@Mixin(ChatComponent.class)
public class ChatLogMixin {
  @Inject(method = "addMessage(Lnet/minecraft/network/chat/Component;)V", at = @At("HEAD"), cancellable = true)
  private void onChatMessage(Component message, CallbackInfo ci) {
    String messageString = message.getString();

    // Always log the chat message to file
    ChatLogger.logMessage(messageString);

    // Check if this is a guild stats message BEFORE processing
    boolean isGuildStats = GuildStateManager.isProcessingModGuildStats() && isGuildStatsMessage(messageString);
    boolean isStaffRankCheck = GuildStateManager.isProcessingModStaffRankCheck() && isStaffRankCheckMessage(messageString);

    // Always process the message for guild info detection (even if we'll suppress it)
    GuildStateManager.processMessage(message, messageString);

    // Hide guild stats output if it was initiated by the mod (not the user)
    if (isGuildStats || isStaffRankCheck) {
      VetsLogger.debug("Suppressing mod-initiated guild stats/rank check message");
      ci.cancel(); // Suppress the message from being displayed
      return;
    }

    // Suppress server feedback for /msg fanout generated by /v.
    if (StaffOutboundMessenger.shouldSuppressFeedback(messageString)) {
      VetsLogger.debug("Suppressed /v outbound feedback line");
      ci.cancel();
      return;
    }

    // Avoid recursively rewriting mod-injected chat messages.
    if (ChatUtils.isInternalDispatch()) {
      return;
    }

    String[] parsedGuildChat = parseGuildChat(messageString);
    if (parsedGuildChat != null) {
      BridgeMessageFetcher.recordServerGuildMessage(parsedGuildChat[0], parsedGuildChat[1]);

      if (BridgeMessageFetcher.isFrumaModeEnabled()
          && BridgeMessageFetcher.wasBridgeMessageRecentlyDisplayed(parsedGuildChat[0], parsedGuildChat[1])) {
        VetsLogger.debug("Suppressed Fruma-mode duplicate from server guild chat");
        ci.cancel();
        return;
      }
    }

    // Rewrite/suppress staff guild alerts (‼ prefixed) into shout-style local output.
    if (StaffGuildAlertRewriter.tryRewrite(messageString)) {
      ci.cancel();
      return;
    }

    // Rewrite lock-prefixed direct messages into /v-style staff chat output.
    if (StaffChannelMessageRewriter.tryRewrite(message, messageString)) {
      ci.cancel();
      return;
    }

    // Rewrite server guild chat messages from supporters with gradient pill styling.
    // Re-entry is blocked by ChatUtils internal dispatch guard above.
    if (ServerGuildChatRewriter.tryRewrite(message, messageString)) {
      ci.cancel();
    }
  }

  private String[] parseGuildChat(String message) {
    int colonIndex = message.indexOf(':');
    if (colonIndex <= 0) {
      return null;
    }

    // Scan forward to find the end of the last custom-font glyph before the
    // colon.  The rank indicator ends with such a glyph; everything after it
    // (trimmed) up to the colon is the display name, which may contain spaces
    // (e.g. "EYAL5555/First Mage").
    int lastGlyphEnd = -1;
    int idx = 0;
    while (idx < colonIndex) {
      int cp = message.codePointAt(idx);
      int charCount = Character.charCount(cp);
      int type = Character.getType(cp);
      boolean isCustomGlyph = type == Character.PRIVATE_USE
          || (type == Character.UNASSIGNED && cp > 0xFFFF);
      if (isCustomGlyph) {
        lastGlyphEnd = idx + charCount;
      }
      idx += charCount;
    }

    if (lastGlyphEnd <= 0 || lastGlyphEnd >= colonIndex) {
      return null;
    }

    String displayName = message.substring(lastGlyphEnd, colonIndex).trim();
    if (displayName.isEmpty()) {
      return null;
    }

    String messageContent = message.substring(colonIndex + 1).trim();
    return new String[] {displayName, messageContent};
  }



  /**
   * Checks if a message is part of the guild stats output
   */
  private boolean isGuildStatsMessage(String message) {
    String trimmed = message.trim();

    // Empty lines are part of guild stats output
    if (trimmed.isEmpty()) {
      return true;
    }

    // Check for guild stats specific content
    return trimmed.contains("Guild Since:") ||
        trimmed.contains("Owner:") ||
        trimmed.contains("Guild Level:") ||
        trimmed.contains("Needed XP:") ||
        trimmed.contains("Guild Rank:") ||
        trimmed.contains("Total Members:") ||
        // Match the guild name line - it's typically just the guild name alone
        trimmed.equals("Returners") ||
        // Match any reasonable guild name pattern (alphanumeric, spaces, underscores, etc.)
        // But exclude MOTD and other formatted messages
        (trimmed.length() > 0 && trimmed.length() < 50 &&
            !trimmed.contains(":") &&
            !trimmed.contains("Welcome") &&
            !trimmed.contains("VETSMOD") &&
            message.matches("^[A-Za-z0-9_ ]+$"));
  }

  /**
   * Checks if a message is part of the /gu rank staff-check output.
   */
  private boolean isStaffRankCheckMessage(String message) {
    String trimmed = message.trim();
    String normalized = trimmed.toLowerCase();
    return (normalized.contains("you must be a") && normalized.contains("captain") && normalized.contains("to use this command")) ||
        (normalized.contains("invalid arguments, try:") && normalized.contains("rank [name] [rank]"));
  }
}
