package org.wynnvets.mixin.client;

import net.minecraft.client.gui.components.ChatComponent;
import net.minecraft.network.chat.Component;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Inject;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfo;
import org.wynnvets.chat.OutboundDisplayHandler;
import org.wynnvets.chat.ChatLogger;
import org.wynnvets.guild.GuildStateManager;
import org.wynnvets.chat.ChatUtils;
import org.wynnvets.chat.rewriter.EncourageUpdateRewriter;
import org.wynnvets.chat.rewriter.ServerGuildChatRewriter;
import org.wynnvets.chat.rewriter.SpoilerRewriter;
import org.wynnvets.chat.rewriter.StaffChannelMessageRewriter;
import org.wynnvets.chat.rewriter.StaffGuildAlertRewriter;
import org.wynnvets.chat.StaffOutboundMessenger;
import org.wynnvets.logging.VetsLogger;

/**
 * Intercepts all incoming chat messages via {@link ChatComponent#addMessage}.
 *
 * <p>This is the primary chat pipeline hook. It performs, in order:
 * logging to file, guild state detection, mod-initiated message suppression,
 * staff outbound feedback suppression,
 * and chat rewriting (staff alerts, staff channel, supporter gradients).
 * Messages generated internally by the mod are passed through unmodified.</p>
 */
@Mixin(ChatComponent.class)
public class ChatLogMixin {
  @Inject(method = "addMessage(Lnet/minecraft/network/chat/Component;)V", at = @At("HEAD"), cancellable = true)
  private void onChatMessage(Component message, CallbackInfo ci) {
    String messageString = message.getString();

    // Skip logging for mod-injected messages (bridge display, rewritten chat, etc.)
    // to prevent a feedback loop where displayed bridge messages are re-sent to the API.
    boolean isInternalDispatch = ChatUtils.isInternalDispatch();

    if (!isInternalDispatch) {
      // Only log externally-sourced chat messages to file and API
      ChatLogger.logMessage(messageString);
    }

    // Process guild check messages first — may suppress /gu stats output
    if (!isInternalDispatch && GuildStateManager.processGuildCheckMessage(messageString)) {
      VetsLogger.debug("Suppressing mod-initiated guild check message");
      ci.cancel();
      return;
    }

    // Check if this is a staff rank-check response BEFORE processing
    boolean isStaffRankCheck = GuildStateManager.isProcessingModStaffRankCheck() && isStaffRankCheckMessage(messageString);

    // Process the message for staff rank detection
    GuildStateManager.processMessage(message, messageString);

    // Hide staff rank check output if it was initiated by the mod (not the user)
    if (isStaffRankCheck) {
      VetsLogger.debug("Suppressing mod-initiated staff rank check message");
      ci.cancel();
      return;
    }

    // Suppress server feedback for /msg fanout generated by /v.
    if (StaffOutboundMessenger.shouldSuppressFeedback(messageString)) {
      VetsLogger.debug("Suppressed /v outbound feedback line");
      ci.cancel();
      return;
    }

    // Suppress server responses to /find commands generated by /wv list world.
    if (StaffOutboundMessenger.shouldSuppressFindResponse(messageString)) {
      VetsLogger.debug("Suppressed /find response line");
      ci.cancel();
      return;
    }

    // Avoid recursively rewriting mod-injected chat messages.
    if (isInternalDispatch) {
      return;
    }

    // Record server guild chat for cross-source dedup.
    String[] parsedGuildChat = parseGuildChat(messageString);
    if (parsedGuildChat != null) {
      OutboundDisplayHandler.recordServerGuildMessage(parsedGuildChat[0], parsedGuildChat[1]);
    }

    // Rewrite encourage-update messages (⚠⚠⚠ ... ⚠⚠⚠) into version status output.
    if (EncourageUpdateRewriter.tryRewrite(message, messageString)) {
      ci.cancel();
      return;
    }

    // Rewrite/suppress staff guild alerts (‼ prefixed) into shout-style local output.
    if (StaffGuildAlertRewriter.tryRewrite(message, messageString)) {
      ci.cancel();
      return;
    }

    // Rewrite lock-prefixed direct messages into /v-style staff chat output.
    if (StaffChannelMessageRewriter.tryRewrite(message, messageString)) {
      ci.cancel();
      return;
    }

    // Rewrite server guild chat messages from supporters with gradient pill styling.
    // Re-entry is blocked by ChatUtils internal dispatch guard above.
    if (ServerGuildChatRewriter.tryRewrite(message, messageString)) {
      ci.cancel();
      return;
    }

    // Rewrite guild chat messages containing ||spoiler|| markers (non-supporters).
    // Supporter messages are already processed above via ServerGuildChatRewriter.
    if (SpoilerRewriter.tryRewrite(message, messageString)) {
      ci.cancel();
    }
  }

  @SuppressWarnings("unused")
  private String[] parseGuildChat(String message) {
    int colonIndex = message.indexOf(':');
    if (colonIndex <= 0) {
      return null;
    }

    // Scan forward to find the end of the last custom-font glyph before the
    // colon.  The rank indicator ends with such a glyph; everything after it
    // (trimmed) up to the colon is the display name, which may contain spaces
    // (e.g. "EYAL5555/First Mage").
    int lastGlyphEnd = -1;
    int idx = 0;
    while (idx < colonIndex) {
      int cp = message.codePointAt(idx);
      int charCount = Character.charCount(cp);
      int type = Character.getType(cp);
      boolean isCustomGlyph = type == Character.PRIVATE_USE
          || (type == Character.UNASSIGNED && cp > 0xFFFF);
      if (isCustomGlyph) {
        lastGlyphEnd = idx + charCount;
      }
      idx += charCount;
    }

    if (lastGlyphEnd <= 0 || lastGlyphEnd >= colonIndex) {
      return null;
    }

    String displayName = message.substring(lastGlyphEnd, colonIndex).trim();
    if (displayName.isEmpty()) {
      return null;
    }

    String messageContent = message.substring(colonIndex + 1).trim();
    return new String[] {displayName, messageContent};
  }


  /**
   * Checks if a message is part of the /gu rank staff-check output.
   */
  private boolean isStaffRankCheckMessage(String message) {
    String trimmed = message.trim();
    String normalized = trimmed.toLowerCase();
    return (normalized.contains("you must be a") && normalized.contains("captain") && normalized.contains("to use this command")) ||
        (normalized.contains("invalid arguments, try:") && normalized.contains("rank [name] [rank]"));
  }
}
