package org.wynnvets.mixin.client;

import net.minecraft.client.gui.components.ChatComponent;
import net.minecraft.network.chat.Component;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Inject;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfo;
import org.wynnvets.util.BridgeMessageFetcher;
import org.wynnvets.util.ChatLogger;
import org.wynnvets.util.GuildInfoListener;
import org.wynnvets.util.chat.ChatUtils;
import org.wynnvets.util.chat.ServerGuildChatRewriter;
import org.wynnvets.util.chat.StaffChannelMessageRewriter;
import org.wynnvets.util.chat.StaffGuildAlertRewriter;
import org.wynnvets.util.chat.StaffOutboundMessenger;

@Mixin(ChatComponent.class)
public class ChatLogMixin {
  @Inject(method = "addMessage(Lnet/minecraft/network/chat/Component;)V", at = @At("HEAD"), cancellable = true)
  private void onChatMessage(Component message, CallbackInfo ci) {
    String messageString = message.getString();

    // Always log the chat message to file
    ChatLogger.logMessage(messageString);

    // Check if this is a guild stats message BEFORE processing
    boolean isGuildStats = GuildInfoListener.isProcessingModGuildStats() && isGuildStatsMessage(messageString);
    boolean isStaffRankCheck = GuildInfoListener.isProcessingModStaffRankCheck() && isStaffRankCheckMessage(messageString);

    // Always process the message for guild info detection (even if we'll suppress it)
    GuildInfoListener.processMessage(message, messageString);

    // Hide guild stats output if it was initiated by the mod (not the user)
    if (isGuildStats || isStaffRankCheck) {
      ci.cancel(); // Suppress the message from being displayed
      return;
    }

    // Suppress server feedback for /msg fanout generated by /v.
    if (StaffOutboundMessenger.shouldSuppressFeedback(messageString)) {
      ci.cancel();
      return;
    }

    // Avoid recursively rewriting mod-injected chat messages.
    if (ChatUtils.isInternalDispatch()) {
      return;
    }

    String[] parsedGuildChat = parseGuildChat(messageString);
    if (parsedGuildChat != null) {
      BridgeMessageFetcher.recordServerGuildMessage(parsedGuildChat[0], parsedGuildChat[1]);

      if (BridgeMessageFetcher.isFrumaModeEnabled()
          && BridgeMessageFetcher.wasBridgeMessageRecentlyDisplayed(parsedGuildChat[0], parsedGuildChat[1])) {
        ci.cancel();
        return;
      }
    }

    // Rewrite/suppress staff guild alerts (‼ prefixed) into shout-style local output.
    if (StaffGuildAlertRewriter.tryRewrite(messageString)) {
      ci.cancel();
      return;
    }

    // Rewrite lock-prefixed direct messages into /v-style staff chat output.
    if (StaffChannelMessageRewriter.tryRewrite(message, messageString)) {
      ci.cancel();
      return;
    }

    // Rewrite server guild chat messages from supporters with gradient pill styling.
    // Re-entry is blocked by ChatUtils internal dispatch guard above.
    if (ServerGuildChatRewriter.tryRewrite(message, messageString)) {
      ci.cancel();
    }
  }

  private String[] parseGuildChat(String message) {
    int colonIndex = message.indexOf(':');
    if (colonIndex <= 0) {
      return null;
    }

    int usernameStart = message.lastIndexOf(' ', colonIndex - 1);
    if (usernameStart <= 0) {
      return null;
    }

    String username = message.substring(usernameStart + 1, colonIndex).trim();
    if (username.isEmpty()) {
      return null;
    }

    int rankStart = message.lastIndexOf(' ', usernameStart - 1);
    if (rankStart <= 0) {
      return null;
    }

    String rankIndicator = message.substring(rankStart + 1, usernameStart).trim();
    if (rankIndicator.isEmpty() || !containsCustomFontGlyph(rankIndicator)) {
      return null;
    }

    String messageContent = message.substring(colonIndex + 1).trim();
    return new String[] {username, messageContent};
  }

  private boolean containsCustomFontGlyph(String text) {
    int index = 0;
    while (index < text.length()) {
      int codePoint = text.codePointAt(index);
      int type = Character.getType(codePoint);
      if (type == Character.PRIVATE_USE
          || (type == Character.UNASSIGNED && codePoint > 0xFFFF)) {
        return true;
      }
      index += Character.charCount(codePoint);
    }
    return false;
  }

  /**
   * Checks if a message is part of the guild stats output
   */
  private boolean isGuildStatsMessage(String message) {
    String trimmed = message.trim();

    // Empty lines are part of guild stats output
    if (trimmed.isEmpty()) {
      return true;
    }

    // Check for guild stats specific content
    return trimmed.contains("Guild Since:") ||
        trimmed.contains("Owner:") ||
        trimmed.contains("Guild Level:") ||
        trimmed.contains("Needed XP:") ||
        trimmed.contains("Guild Rank:") ||
        trimmed.contains("Total Members:") ||
        // Match the guild name line - it's typically just the guild name alone
        trimmed.equals("Returners") ||
        // Match any reasonable guild name pattern (alphanumeric, spaces, underscores, etc.)
        // But exclude MOTD and other formatted messages
        (trimmed.length() > 0 && trimmed.length() < 50 &&
            !trimmed.contains(":") &&
            !trimmed.contains("Welcome") &&
            !trimmed.contains("VETSMOD") &&
            message.matches("^[A-Za-z0-9_ ]+$"));
  }

  /**
   * Checks if a message is part of the /gu rank staff-check output.
   */
  private boolean isStaffRankCheckMessage(String message) {
    String trimmed = message.trim();
    String normalized = trimmed.toLowerCase();
    return (normalized.contains("you must be a") && normalized.contains("captain") && normalized.contains("to use this command")) ||
        (normalized.contains("invalid arguments, try:") && normalized.contains("rank [name] [rank]"));
  }
}
